### ISSUE TITLE
Recent Update - Traffic Sent/Received

### ISSUE THREAD

**Issue by daygle** [duy13/vDDoS-Protection#14]
I think your recent update allowing swap may have broken something else, have a look at the screenshot from the monitor window:-

![image](https://user-images.githubusercontent.com/5925233/33348816-e442adfe-d4eb-11e7-8fac-bab4c6c5aefd.png)

**Comment by duy13** [comment]
Contact me directly for assistance

**Comment by duy13** [comment]
http://nginx-win.ecsds.eu/download/Readme%20nginx-win%20version.txt

```
IE is displaying "NaN" and "NaN GiB"
  see 'Cache-Control' in conf\vhts\VHTS.txt

```
Please use another browser (not Microsoft IE, Edge)
