### ISSUE TITLE
SPDY Error with Applications

### ISSUE THREAD

**Issue by WebsecAkhavan** [duy13/vDDoS-Protection#15]
Please enable an option to disable SPDY since it causes errors with Sockets in some applications (err_spdy_protocol_error in browser console)

**Comment by duy13** [comment]
Please increase the limit values to fit your site:


```
nano /vddos/conf.d/limit-conn.conf

limit_conn_zone $binary_remote_addr zone=perip:10m;
limit_conn perip 100;
limit_conn_status 403;
limit_req_zone $binary_remote_addr zone=dyn:10m rate=100r/s;
limit_req zone=dyn burst=100;
limit_req_status 403;

```

Or more, if your web site needs to load more resources in a single query
