### ISSUE TITLE
Setting for Varnish Nginx and Apache 

### ISSUE THREAD

**Issue by rivai1** [duy13/vDDoS-Protection#18]
How to setting in website.conf if I using 
Varnish ->Nginx->Apache

Http Port 
Varnish : 82
Nginx : 80
Apache : 8181

SSL Port 
Varnish : 82
Nginx : 443
Apache : 8443

I use varnish for caching and nginx as reverse proxy

**Comment by duy13** [comment]
You should remove nginx; If the varnish is not needed you should also remove:

The system will be: vDDoS > Varnish (if exists) > Apache

Http Port
Varnish : 82
vDDoS : 80
Apache : 8181

SSL Port
Varnish : 82
vDDoS : 443
Apache : 8443
