### ISSUE TITLE
IPV6

### ISSUE THREAD

**Issue by hostingfuze** [duy13/vDDoS-Protection#20]
ipv6 work ?

**Comment by duy13** [comment]
Sorry, IPv6 is not currently supported, will update in the new version, I will notify you later

**Comment by hostingfuze** [comment]
until then for ipv6 I will try with standard nginx. Thanks and I look forward to the following compatible versions.

**Comment by duy13** [comment]
IPv6 support from vDDoS 1.13.10
https://github.com/duy13/vDDoS-Protection/blob/master/CHANGELOG.txt
