### ISSUE TITLE
How to get really ip

### ISSUE THREAD

**Issue by Oceanlotus** [duy13/vDDoS-Protection#21]
Hellow
Vddos is a really amazing software，But after use vddos,I can't get really ip. What I should do?

Thanks

**Comment by duy13** [comment]
WITH APACHE:
```
RemoteIPHeader X-Forwarded-For
RemoteIPTrustedProxy 192.168.1.10 10.10.0.1
```
https://www.globo.tech/learning-center/x-forwarded-for-ip-apache-web-server/

WITH NGINX:
```
set_real_ip_from 192.168.1.10;
set_real_ip_from 10.10.0.1;
real_ip_header X-Forwarded-For;

```
https://ypereirareis.github.io/blog/2017/02/15/nginx-real-ip-behind-nginx-reverse-proxy/
