### ISSUE TITLE
404 error with reCAPTCHA mode

### ISSUE THREAD

**Issue by robert1112** [duy13/vDDoS-Protection#23]
Hi 

I used captcha in /vddos/conf.d/website.conf and `vddos restart`. It asked to fill up the sitekey and private key in  /vddos/conf.d/recaptcha-sitekey.conf and /vddos/conf.d/recaptcha-secretkey.conf. and I did what is asked. 

reCAPTCHA is shown correctly on the front but after tick it and verified, I got 404 error. 

I also got the error on https://www.google.com/recaptcha/admin

> We detected that your site is not verifying reCAPTCHA solutions. This is required for the proper use of reCAPTCHA on your site. Please see our developer site for more information.

Is it because it didnt pass along reCAPTCHA to Google? Please Kindly help. Thank you.

**Comment by robert1112** [comment]
```
cat /vddos/conf.d/recaptcha-sitekey.conf
# Website		reCaptcha-sitekey (View KEY in https://www.google.com/recaptcha/admin#list)
ddos.dreambox.tw    6LfkrFEUAAAAAG4E3_9Lb-Xmn4zRaRk3U5t8rsJs
```
```
cat /vddos/conf.d/recaptcha-secretkey.conf
DEBUG=True
RE_SECRETS = { 'ddos.dreambox.tw': '6LfkrFEUAAAAAFWyTbLDnUGtjMa7SEqiVJHGTn1M',
               'your-domain2.com': 'per_domain_recaptcha_secret_key2' }
```
```
cat /vddos/conf.d/website.conf
# Website       Listen               Backend                     Cache Security SSL-Prikey   SSL-CRTkey
ddos.dreambox.tw   http://0.0.0.0:80    http://35.194.221.246:80    no   high      no           no
ddos.dreambox.tw   https://0.0.0.0:443  https://35.194.221.246:443   no  high   /vddos/ssl/your-domain.com.pri /vddos/ssl/your-domain.com.crt
```
netstat -lntup|grep python return blank

```
curl -I https://www.google.com/recaptcha/api
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Date: Sun, 08 Apr 2018 09:43:45 GMT
Expires: Sun, 08 Apr 2018 09:43:45 GMT
Cache-Control: private, max-age=0
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Transfer-Encoding: chunked
Accept-Ranges: none
Vary: Accept-Encoding
```
and I tried to stop and start vDDOS. I got the output.
```
vddos start
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] still could not bind()
(Defensive Estimating ~ 34 RealReq/s)
0.0.0.0:80
0.0.0.0:443
vDDos service Restart success!
```
Thank you so much for your prompt reply.

**Comment by duy13** [comment]
`netstat -lntup|grep python return blank`

this is a problem, please reinstall vDDoS, your python has failed

**Comment by robert1112** [comment]
Hi @duy13  Thanks for your advice. I reinstalled the latest python 3.6.4 and reinstalled vDDOS but I still got blank output of the command `netstat -lntup|grep python` Please kindly advice, thank you so much.

**Comment by duy13** [comment]
You do not need to install python 3.6.4; 
vDDoS will install its python itself; 
Please reinstall the operating system and install vDDoS again

**Comment by robert1112** [comment]
Hi @duy13 That is weird. Because I did install vDDOS first and check python but stilll blank,  that is why I tried to install myself. I will try with a fresh server as you suggested. Thank you,

**Comment by robert1112** [comment]
Hi @duy13  I started with a fresh Cento7 server and follow the commands on vDDOS homepage and I got confirmation output that vDDOS and python is successfully installed. But I still out blank output by running  `netstat -lntup|grep python` I don't know what is going wrong? Please kindly advice. Thanks for your support.

**Comment by duy13** [comment]
Reinstall the operating system, send me ssh root information, i will proceed with the installation for you to look up the error on your system.

**Comment by duy13** [comment]
Solved!
The problem caused by SSH terminal of Mac OS when using Google Cloud VM
If you encounter this problem please login with root user + password (do not use keygen)
