### ISSUE TITLE
Error: your browser is too old to work on this website

### ISSUE THREAD

**Issue by robert1112** [duy13/vDDoS-Protection#24]
Hi I got the error : Unfortunately, your browser is too old to work on this website while using "high"
security level. I am sure I update Safari(Mac OS) to the latest. Please Kindly help. Thank you.

<a href="https://ibb.co/nO9Rz7"><img src="https://preview.ibb.co/mqZte7/Screen_Shot_2018_04_13_at_1_59_24_PM.png" alt="Screen_Shot_2018_04_13_at_1_59_24_PM" border="0"></a>

**Comment by duy13** [comment]
Solved!
Turn off any cache configuration on CloudFlare (especially javascript cache) when using vDDoS + CloudFlare

**Comment by robert1112** [comment]
Hi @duy13 

The issue occurred again. Here is the setting on Cloudflare.

Browser Cache Expiration: Respect Existing Header
Auto Minify: OFF

Thank you.
