### ISSUE TITLE
How to correctly whitelist IPs?

### ISSUE THREAD

**Issue by robert1112** [duy13/vDDoS-Protection#29]
Hi @duy13 

I tried 2 methods to whitelist my IP. One is `whitelist-botsearch.conf` . Second is `/vddos/conf.d/cus/dreambox.tw.location.conf`. Both are not working. I still got challenged from time to time due to multiple query operation on backend. ( I think that is the reason why I got suspected)

Please Kindly help. Thank you very much.

**Comment by duy13** [comment]
Please `cat whitelist-botsearch.conf` & `cat dreambox.tw.location.conf`

**Comment by robert1112** [comment]
`cat whitelist-botsearch.conf` 
```
 # My IP
122.122.123.12
`
`dreambox.tw.location.conf` is very silly try. :D

**Comment by duy13** [comment]
```
	# Alexa Bot IP Addresses
204.236.235.245; 75.101.186.145;
	# My IP
122.122.123.12;
```
