### ISSUE TITLE
ERROR START

### ISSUE THREAD

**Issue by alexnetwork** [duy13/vDDoS-Protection#34]
Hi,
Error:
/etc/init.d/vdos status
● vdos.service - SYSV: vddos is an HTTP(S) DDoS Protection Reverse Proxy
   Loaded: loaded (/etc/rc.d/init.d/vdos; bad; vendor preset: disabled)
   Active: failed (Result: resources) since sab 2018-06-16 06:58:14 EDT; 1min 21s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2100 ExecStart=/etc/rc.d/init.d/vdos start (code=exited, status=0/SUCCESS)

giu 16 06:58:14 node1-s1-antiddos-l7 systemd[1]: Starting SYSV: vddos is an HTTP(S) DDoS Protection Reverse Proxy...
giu 16 06:58:14 node1-s1-antiddos-l7 systemd[1]: PID file /var/run/vddos.pid not readable (yet?) after start.
giu 16 06:58:14 node1-s1-antiddos-l7 systemd[1]: Failed to start SYSV: vddos is an HTTP(S) DDoS Protection Reverse Proxy.
giu 16 06:58:14 node1-s1-antiddos-l7 systemd[1]: Unit vdos.service entered failed state.
giu 16 06:58:14 node1-s1-antiddos-l7 systemd[1]: vdos.service failed.

WHY?

**Comment by duy13** [comment]
**/etc/init.d/vdos** is only used for errors-checking developers; with the users, you just only use **/usr/bin/vddos**
