### ISSUE TITLE
Cloudflare Authenticated Origin Pulls will impact on vddos Proxy?

### ISSUE THREAD

**Issue by robert1112** [duy13/vDDoS-Protection#36]
Hi  Duy,

How are you doing? Hope all is good.

If I enable Authenticated Origin Pulls on Cloudflare, will it affect function of vddos Proxy? This prevents clients from sending requests directly to your origin, bypassing security measures provided by Cloudflare, such as IP and Web Application Firewalls, logging, and encryption. 

Thanks.

**Comment by duy13** [comment]
With my point of view this feature is not important unless you use cloudflare and a hosting package but are leaking the original IP. What if your website still has port 80 and the attacker can go into it directly?
If the Original IP address was leaked, there is only one effective way to prevent the connection coming from all IP ranges except for the Cloudflare IP.
vDDoS will not offer this feature in the near future
