### ISSUE TITLE
cPanel test

### ISSUE THREAD

**Issue by hostingfuze** [duy13/vDDoS-Protection#37]
there are many cpanel errors, such as:

- does not read the dedicated ip address
- does not read the ssl certificate
and more .
We are waiting for new versions!

reference : http://www.webhostingtalk.com/showthread.php?t=1715221

**Comment by duy13** [comment]
```
"does not read the dedicated ip address"
```
Refer to the command for adding a domain: 

"Or specify custom information:"
```
/usr/bin/vddos-autoadd [domain] Website="your-domain.com" Cache="no" Security="no" HTTP_Listen="http://0.0.0.0:80" HTTPS_Listen="https://0.0.0.0:443" HTTP_Backend="http://127.0.0.1:8080" HTTPS_Backend="https://127.0.0.1:8443"
```
https://github.com/duy13/vDDoS-Auto-Add#add-a-domain

Trying to write a crontab automatically identifies the dedicated ip address from cpanel and adds it to vDDoS
Besides, in my opinion, configuring a domain to be listened to on 0.0.0.0 does not cause any problems.


```
"does not read the ssl certificate"
```


You should find out how vDDoS works with let's encrypt, and how to add ssl to vDDoS, 
https://github.com/duy13/vDDoS-Auto-Add#4-crontab-vddos-auto-add

it looks like vDDoS will not support too many custom features you need (for example a cpanel user uploads the ssl file and it self dynamically added to vDDoS)
The number of users vDDoS + cpanel is quite small and I do not have time to serve this feature
```
"We are waiting for new versions!"
```
Seems like these features will not be available in the coming months, vDDoS-Auto-Add will help you automate some basic stuff, and with things as advanced as you requested, I would not have plenty of time for them.

**Comment by hostingfuze** [comment]
with 127.0.0.1 opens the cPanel default page. the required IP address is required!

**Comment by duy13** [comment]
```
HTTP_Backend="http://127.0.0.1:8080" HTTPS_Backend="https://127.0.0.1:8443"
```
I mean you need to replace that part accordingly
