### ISSUE TITLE
Error! Captcha error!

### ISSUE THREAD

**Issue by alexnetwork** [duy13/vDDoS-Protection#41]
Hi,
As soon as vDDoS is enabled all the sites with the recap are giving this error: Error! Captcha error!
Why?

**Comment by alexnetwork** [comment]
The problem only happens with sites with HTML re-captcha.

**Comment by alexnetwork** [comment]
<script src='https://www.google.com/recaptcha/api.js'></script>
<div class="g-recaptcha" data-sitekey="key"></div>
<div id="response"></div>
Without vDDoS not problems.

**Comment by ARIS-GREECE** [comment]
### You need to create your own site-key & secret-key for each website

https://www.google.com/recaptcha/admin
**Register a new site** > [ **I use the** ]: **reCAPTCHA v2** > **Checkbox**
Fill in the fields with their domains and subdomains below
and you get for each domain its own site-key and its own secret-key,
yes you have to do that for every domain

what you have to do to add the site-key & secret-key is included
go in the directory `/vddos/conf.d` 
you have to edit the file `recaptcha.conf`

```
# (View KEY in https://www.google.com/recaptcha/admin#list)
# Website	reCaptcha-sitekey		reCaptcha-secretkey


###
# example.com # for a normal domain 
example.com <reCaptcha-sitekey> <reCaptcha-secretkey>
###

###
# www.example.com # for a subdomain
www.example.com <reCaptcha-sitekey> <reCaptcha-secretkey>
###

###
# sub.example.com # for a subdomain
sub.example.com <reCaptcha-sitekey> <reCaptcha-secretkey>
###
```

and now you need to restart vDDos reverse proxy
connect via SSH and give this command in the command line `vddos restart`

**Comment by ARIS-GREECE** [comment]
### I use CloudFlare reCaptcha.
with vDDoS [ `vDDoS Layer4` ]
**https://github.com/duy13/vDDoS-Layer4-Mapping**

so I do not have to make site-key & secret-key,
other visitors can not see their IP address through CloudFlare,
ihre Server IP-Adresse wird nicht sichtbar sein für andere Besucher,

### Disadvantages of CloudFlare reCAPTCHA

Your visitors will see that they use CloudFlare.

### vDDos Layer4 Mapping:

![](https://lh4.googleusercontent.com/-1yUKjjGxUug/WHg5SobZHSI/AAAAAAAAA-k/SOIpKjRe8wsih9xybHMpq6ieQ8wPnukCQCLcB/s1600/vDDoS-layer4-mapping-cloudflare.png)
image: http://vddos.voduy.com/

**Comment by ARIS-GREECE** [comment]
CloudFlare reCaptcha has solved all my problems.

with vDDoS [ `vDDoS Layer4` ]
**https://github.com/duy13/vDDoS-Layer4-Mapping**

**Comment by alexnetwork** [comment]
I use invisible delivery and it works on vDDoS. the problem occurs in the sites that use the recapcha with only the sitekey (HTML version) that stop working by giving: Error. But vDDoS still works. It must be something that vDDoS blocks.

**Comment by duy13** [comment]
Are you sure at the backend can identify the query real IP behind the proxy vDDOS; If recaptcha only sees one IP address vDDOS proxy query comes it, that is a big problem. 
The information you provide is too small, I need to know more to determine the problem. Contact my skype
