### ISSUE TITLE
StackPath CDN

### ISSUE THREAD

**Issue by wafedsf5** [duy13/vDDoS-Protection#44]
Im trying to use a CDN called StackPath, I allowed all stackpath IPs but sadly it doesn't work.
When I start using stackpath the protection gets into a infinite loop until it reachs d5 and give the error.
Can you check it by yourself? (stackpath ahve 30 days trial so you can test)

**Comment by duy13** [comment]
Allow IP range of CDN
Disable cache js
Contact my skype **voduy13**
