### ISSUE TITLE
redirect doesnt work anymore?

### ISSUE THREAD

**Issue by szkuta** [duy13/vDDoS-Protection#45]
tried to add the following lines into 
/vddos/conf.d/redirect.conf
/vddos/conf.d/domain/pimmelbande.fun/redirect.conf
/vddos/conf.d/domain/www.pimmelbande.fun/redirect.conf

`if ($schemedomain = "http://pimmelbande.fun") {
    return 301 https://pimmelbande.fun$request_uri;
}
if ($schemedomain = "http://www.pimmelbande.fun") {
    return 301 https://pimmelbande.fun$request_uri;
}
if ($schemedomain = "https://www.pimmelbande.fun") {
    return 301 https://pimmelbande.fun$request_uri;
}`

but doesnt work

try it: https://www.pimmelbande.fun/

**Comment by duy13** [comment]
+The redirect is no longer configured at /vddos/conf.d/redirect.conf
+/vddos/conf.d/redirect.conf is currently just a template
+Please:
1.  return /vddos/conf.d/redirect.conf to the prototype version
2. Remove `rm -rf /vddos/conf.d/domain`
3. vddos restart
4. config redirect for each website in its directory (/vddos/conf.d/domain/pimmelbande.fun/redirect.conf)
5. vddos reload

**Comment by szkuta** [comment]
yes but this method doesnt work for me^^ i already tried that

**Comment by szkuta** [comment]
found my mistake
anyway thanks for your support
