### ISSUE TITLE
Ubuntu Please :((

### ISSUE THREAD

**Issue by khokooli** [duy13/vDDoS-Protection#46]
why this is not available for Ubuntu ? 
add a package for Ubuntu Please :( 
I don't understand , why not Ubuntu ?? 

also , is there any documentation for compile it from source code ? 
and what is vDDoS Auto Add and vDDoS Auto Switch ?

**Comment by joglomedia** [comment]
Basically it is Nginx as reverse proxy, may be you can adopt its configuration to your Nginx install
