### ISSUE TITLE
Your vDDOS is the best.But I have a question.

### ISSUE THREAD

**Issue by freechalph** [duy13/vDDoS-Protection#50]
I am using vDDOS. I am installing and using 2 servers, but I want to install 1 more. But there is an error. Check the error in the image below.
Did you end your support?

Please tell me the solution.
![image001](https://user-images.githubusercontent.com/57882438/69020472-ee6e4e80-09f7-11ea-9c42-60c25168eb55.png)

**Comment by duy13** [comment]
It is possible that the github server has a problem, you cannot download ***.tar.gz** file
I have updated the sourceforge server, hope everything is fine

[https://sourceforge.net/projects/vddos-protection](https://sourceforge.net/projects/vddos-protection)
