### ISSUE TITLE
uninstall vddos

### ISSUE THREAD

**Issue by NuggaN85** [duy13/vDDoS-Protection#58]
how to uninstall it because it doesn't work at all it takes too much server load but it doesn't do anything behind it hasn't blocked anything for a week I have a backup but it doesn't do anything or explain how to set it up properly because for me it doesn't work I'm under centos 8

**Comment by duy13** [comment]
vui lòng đọc kỹ: [vDDoS only supports CentOS Server 7](https://github.com/duy13/vDDoS-Protection#system-requirement)

**Comment by NuggaN85** [comment]
> Please read carefully:: [vDDoS only supports CentOS Server 7](https://github.com/duy13/vDDoS-Protection#system-requirement)

yes I read everything from a.z I'm on centos7 so the requirement is good but nothing works I've done some tests and it doesn't block anything

**Comment by duy13** [comment]
You should contact directly, let me guide you to use: **Skype/Telegram: voduy13**

**Comment by duy13** [comment]
Problem solved: You don't know how to integrate vDDOS into WHM/cPanel
Please refer to instructions here: [www.webhostingtalk.com/showthread.php?t=1715221](https://www.webhostingtalk.com/showthread.php?t=1715221)

**Comment by NuggaN85** [comment]
> Problem solved: You don't know how to integrate vDDOS into WHM/cPanel
> Please refer to instructions here: [www.webhostingtalk.com/showthread.php?t=1715221](https://www.webhostingtalk.com/showthread.php?t=1715221)

the manipulation you've done with me so I know where to uninstall it and make it clean?

**Comment by duy13** [comment]
Besides, for those who are looking for a way to thoroughly uninstall vDDOS:

```
vddos stop
rm -rf /vddos
rm -rf /usr/lib64/vddos/modules
rm -rf /var/log/vddos
rm -rf /var/cache/vddos
rm -rf /usr/bin/vddos*
```
