### ISSUE TITLE
bad ssl

### ISSUE THREAD

**Issue by glebkhil** [duy13/vDDoS-Protection#61]
Why, after the release of ssl, does it still write "the connection is not protected"? How to fix everything creates files

**Comment by R00tS3c** [comment]
Wrong SSL cert or you are not configure correct path

**Comment by glebkhil** [comment]
there is an instruction on how to configure under cyberpanel? In the properties of the certificate, he writes that it was issued by my domain and not by the certification service

**Comment by glebkhil** [comment]
vddos generates a self-signed certificate. I need a normal certificate, how can I do it?

**Comment by duy13** [comment]
https://github.com/duy13/vDDoS-Auto-Add/blob/a4551bff256e4c9b14ebd903b7456bbc177e4d77/cron.sh#L39

**Comment by glebkhil** [comment]
> https://github.com/duy13/vDDoS-Auto-Add/blob/a4551bff256e4c9b14ebd903b7456bbc177e4d77/cron.sh#L39

this command creates a self-signed certificate for me. I reconfigured and I already have a link from letsencrypt, but when I switch to a domain, I get a 404 error. I use cyperpanel and a liteSpeed server

**Comment by glebkhil** [comment]
i found the problem and solved it, thanks

**Comment by R00tS3c** [comment]
close issue
