### ISSUE TITLE
Installing the wrong SSL for the website.

### ISSUE THREAD

**Issue by 007basaran** [duy13/vDDoS-Protection#62]
Hello,

Today I received Layer 7 attacks with very high requests and I was thinking of making a proxy system over nginx to prevent this, while I was searching I came across vDDOS, this was very good.

I configured some servers with vDDOS software, and i test vDDOS anti ddos techniques, i just say, this is awesome perfect. Maybe more time after we can develope more this software and we can add automation for CWP like control panels. 

Firstly i thank you for this software, this software is want very time effort.

For nowly i only see one issue, the issue is SSL Certificates. 

My website.conf file content, example domains (anotherdomain.com-otherdomain.com). :

> anotherdomain.com http://0.0.0.0:80 http://X.X.X.X:9080 yes high no no
> anotherdomain.com https://0.0.0.0:443 https://X.X.X.X:9443 yes high /etc/pki/tls/private/anotherdomain.com.key /etc/pki/tls/certs/anotherdomain.com.cert
> 
> otherdomain.com http://0.0.0.0:80 http://X.X.X.X:9080 yes high no no
> otherdomain.com https://0.0.0.0:443 https://X.X.X.X:9443 yes high /etc/pki/tls/private/otherdomain.com.key /etc/pki/tls/certs/otherdomain.com.cert

What is the full description of the problem?

For example, when the system has two or more domains, it tries to use the SSL Certificate file of the other domain name for the site you are logging into.

For example, I am accessing anotherdomain.com, but i see https error, because otherdomain.com certificate activated for anotherdomain.com. 

When i access exampledomain.com web site, i see exampledomaintwo.com ssl certificate, this is the problem.

Thank you for your answer in advance.

**Comment by duy13** [comment]
check error log

**Comment by 007basaran** [comment]
Hello again,

I checked all log files, for the issue with SSL Certificate, I couldn't find any error content.

**Comment by duy13** [comment]
change ssl in cloudflare to Full
![images](https://user-images.githubusercontent.com/10364660/128126450-c51b6138-5207-4e47-b3c2-80b5e689ae5b.png)

**Comment by 007basaran** [comment]
Hello again,

We do not use Cloudflare Proxy, the sites are located within the server itself. 

For example, let's say there are 2 records in the website.conf file, one is hostname and the other is domain. The ssl certificate that I have specified in the website.conf file for these two domains comes without any problems. There is nothing wrong. But when a 3rd domain is added, the ssl certificate determined for this added 3rd domain changes the ssl certificate of the 2nd domain, that is, the 2nd domain tries to get the certificate of the 3rd domain address added.

**Comment by 007basaran** [comment]
Maybe i need change website.conf file system, how can i do this; i cant see in source.

**Comment by duy13** [comment]
Contact me directly to check

**Comment by duy13** [comment]
declare missing **www** in **website.conf** -> solved
