### ISSUE TITLE
No Memory in Vhost

### ISSUE THREAD

**Issue by daygle** [duy13/vDDoS-Protection#7]
I seem to be receiving a number of the below messages in my /var/log/vddos/error log, would anyone have any suggestions on how to correct this?

2017/07/08 17:25:17 [crit] 10671#10671: ngx_slab_alloc() failed: no memory in vhost_traffic_status_zone "ngx_http_vhost_traffic_status"

**Comment by duy13** [comment]
```
[root@vddos ~]# cat /vddos/vDDoS_Monitor.txt
 vDDoS Admin Monitor: http://7.14.11.28/3ac31763-vddos-monitor
 vDDoS Admin Monitor TCP/UDP: http://7.14.11.28/43ac331763-tcp-udp-vddos-monitor
...
```

Because your website has too many logs and exceeds the allowed memory limit in vDDoS_Monitor

To clear all the memo data in vDDoS_Monitor, please go to [Example:] `http://7.14.11.28/3ac31763-vddos-monitor/control?cmd=delete&group=*`

Or just `vddos restart`

I will try to fix this problem in the new version

**Comment by daygle** [comment]
Thank you so much for getting back to me.

Ok so this seems to be a known issue, maybe I should schedule a command that performs a vddos restart every hour until this is corrected? Or are you able to recommend another crontab command?

Look forward to seeing this corrected in the next release.

**Comment by duy13** [comment]
Crontab `curl -L http://7.14.11.28/3ac31763-vddos-monitor/control?cmd=delete&group=*`

Every a hour

**Comment by daygle** [comment]
Unfortunately the above command isn't working, it seems that you need an enter after the curl statement is run. Even when a enter is added it still doesn't flush.

That said, it works in a browser outside of the server hosting vddos.

Any other ideas?

**Comment by duy13** [comment]
Try update vDDoS 1.13.2

**Comment by daygle** [comment]
Oh wow! Thanks.

Could you please provide me the recommended upgrade instructions.

**Comment by daygle** [comment]
Ok I ended up finding the updrage/reinstall instructions here:- https://www.lowendtalk.com/discussion/100518

That said, after upgraing although everything seems ok I am now receiving numerious of the original reported error in my /var/log/vddos/error.log (a few every minute).

**Comment by duy13** [comment]
#Save old config:
`mv /vddos/conf.d/website.conf ~/
`
#Remove:

```
rm -rf /vddos
rm -rf /usr/lib64/vddos/modules
rm -rf /var/log/vddos
rm -rf /var/cache/vddos

```
#ReInstall vDDoS new version:
```
curl -L https://github.com/duy13/vDDoS-Protection/raw/master/vddos-1.13.2-centos7 -o /usr/bin/vddos
chmod 700 /usr/bin/vddos
/usr/bin/vddos help
/usr/bin/vddos setup

```
#Restore config:
`mv ~/website.conf /vddos/conf.d/`

#Restart vDDoS:
`vddos restart`

**Comment by duy13** [comment]
`That said, after upgraing although everything seems ok I am now receiving numerious of the original reported error in my /var/log/vddos/error.log (a few every minute).
`
Can You contact me (**skype voduy13**)

**Comment by daygle** [comment]
Thanks for your time today. Unfortunately that cron you setup isn't working. Errors are still appearing non stop, I had to in fact create another cron to clear the error log every 30 minutes.

Maybe you need to remove the live stats page to prevent the error from appearing in the logs or have an option to turn live stats off or on?

**Comment by daygle** [comment]
It seems this issue has been resolved with the latest version, I'll close this issue.
