### ISSUE TITLE
Unwanted files from Voduy website

### ISSUE THREAD

**Issue by wiseweb-works** [duy13/vDDoS-Protection#75]
While browsing the files section of your website, I noticed unwanted files in the "www" folder, possibly uploaded by others. I don't think it is actively used. But I still think it's good to delete it.

![image](https://user-images.githubusercontent.com/69072094/188686225-5c7b6422-6b1e-4543-ba9b-713a7f9bc86f.png)

**Comment by duy13** [comment]
I uploaded them a few years ago, they are used to test the hosting environment as needed. some use to check localattack, some to check php version, user permissions...
As you can see, they are in **.txt** format, people can view their content
