### ISSUE TITLE
Configuration issue with IPv6 address

### ISSUE THREAD

**Issue by m8522s** [duy13/vDDoS-Protection#78]
Hi,

I'm trying to set up vDDoS 2.3.3 as an IPv6 reverse proxy. My configuration file `/vddos/conf.d/website.conf` contains a single config line:

```
# Website Listen          Backend                Cache  Security  SSL-Prikey  SSL-CRTkey
default   http://[::]:80  http://[fd00:5::81]:80 no     no        no          no
```

However, when starting vDDoS with `vddos restart` I get the error message:
```
ERROR!ing line: 2 in website.conf
http://[::]:80 line 2 in /vddos/conf.d/website.conf
Please choose a valid for Listen type: http://0.0.0.0:80|https://[::]:443|...
```

What is the correct syntax for a IPv6 configuration line?
Issue #42 suggests config file `/vddos/conf.d/cus/vddos.conf`, but I didn't see any relevant information.

Thanks for your help!

**Comment by duy13** [comment]
```
[root@ ~]# cat /vddos/conf.d/cus/vddos.conf
ipv6_support: no                                                #Enable/Disable IPv6 (Option: yes or no)
```

**Comment by m8522s** [comment]
That works. Thanks for pointing me in the right direction.
