### ISSUE TITLE
cat: /var/run/vddos.pid: No such file or directory

### ISSUE THREAD

**Issue by awab228** [duy13/vDDoS-Protection#82]
Hello, after first install it works ok, but after system reboot i get this error when i try to start it

`(Defensive Estimating ~ 4369 RealReq/s)
cat: /var/run/vddos.pid: No such file or directory
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
vDDoS service Start success!`

removing and reinstalling doesn’t help, i am using "Almalinux 8 "

**Comment by awab228** [comment]
also when trying to run `vddos setup ` this error appears `root@vddos:~# vddos setup
Error! Missing lib...`

**Comment by awab228** [comment]
i did install using the `wget https://raw.githubusercontent.com/duy13/vDDoS-Protection/master/latest.sh ; chmod 700 latest.sh ; bash latest.sh` so its the latest version

**Comment by duy13** [comment]
cat /var/log/vddos/error.log
